In [23]:
def fc_count(a):
    c=0
    for i in range(1,a+1):
        if a %i==0:
            c=c+1
        return c

In [25]:
def isprime(a):
    fc=f_count(a)
    if fc==2:
        return True
        return False

In [29]:
i=int(input())
if isprime(i):
    print("prime")
else:
    print('not')

3


NameError: name 'f_count' is not defined

In [93]:
def primes(n):
    if n<2:
        return False
    for i in range(2,n//2+1):
        if n%i==0:
            return False
    return True
primes(6)


False

### Maps:
syntax: map(function,iterable)

In [33]:
l=['1','2','3','4']
l1=[]
for i in l:
    j=int(i)
    l1.append(j)
print(l1)

[1, 2, 3, 4]


In [34]:
list(map(int,l))

[1, 2, 3, 4]

In [35]:
list(map(str,l))

['1', '2', '3', '4']

In [44]:
i=input().split()

python program


In [47]:
i=input().split()

python program


In [51]:
list(map(int,input()))

123145584645


[1, 2, 3, 1, 4, 5, 5, 8, 4, 6, 4, 5]

In [53]:
def addition(n):
    return n+n
addition(5)

10

In [54]:
list(map(addition,[1,5,6,4,8,5]))

[2, 10, 12, 8, 16, 10]

In [57]:
def power(n):
    return n**n


In [59]:
list(map(power,[1,5,6,4,8,5]))

[1, 3125, 46656, 256, 16777216, 3125]

In [62]:
def sqrt(n):
    return n*n
l=list(map(sqrt,[1,2,3,4,5,6,7,8,9,10]))
for i in l:
    print(i)

1
4
9
16
25
36
49
64
81
100


### Filters

In [91]:
Li=[1,2,5,6,17,101,3]
def isDigit(n):
    n=str(n)
    if n.isdigit():
        return True
    return False
list(filter(isDigit,Li))
list(filter(primes,Li))

[2, 5, 17, 101, 3]

In [81]:
def even(n):
    if n%2==0:
        return  True


In [82]:
list(filter(even,Li))

[2, 6]

In [83]:
def odd(n):
    if n%2!=0:
        return  True


In [84]:
list(filter(odd,Li))

[1, 5, 17, 101, 3]

### lambda

In [94]:
h=lambda x :x%2==0
list(filter(h,[1,2,3,4,5,6]))  

[2, 4, 6]

In [98]:
l=[1,2,3,4,5,6,7,8,9,10]
o=lambda i:i%2!=0
list(filter(o,l))

[1, 3, 5, 7, 9]

In [100]:
from random import randint as r 
for  i in range(1,10+1):
    print(r(1,25))
    

12
11
8
13
22
24
21
12
21
5


In [102]:
m1=[r(1,25)for i in range(1,11)]
m2=[r(1,25)for i in range(1,11)]
m3=[r(1,25)for i in range(1,11)]
print(m1)
print(m2)
print(m3)

[1, 5, 4, 21, 3, 17, 6, 14, 1, 11]
[19, 2, 22, 24, 13, 15, 9, 17, 2, 7]
[20, 10, 22, 25, 12, 6, 11, 7, 20, 19]


In [118]:
a1=list(map(lambda x,y:(x+y)//2,m1,m2))
print(a1)

[10, 3, 13, 22, 8, 16, 7, 15, 1, 9]


In [121]:
a2=list(map(lambda x,y,z:(x+y+z)//3,m1,m2,m3))
print(a2)

[13, 5, 16, 23, 9, 12, 8, 12, 7, 12]


In [119]:
k=lambda x:x<10
list(filter(k,a1))

[3, 8, 7, 1, 9]

In [123]:
g=lambda x:x<10
list(filter(g,a2))

[5, 9, 8, 7]

## Numpy

In [124]:
import numpy as np

In [132]:
l=[1,2,3,4]
a1=np.array(l)
print(a1)

[1 2 3 4]


In [131]:
k=[[1,2,3,4],[1,2,3,4]]
a2=np.array(k)
print(a2)

[[1 2 3 4]
 [1 2 3 4]]


In [129]:
j=[[1,2,3,4],[1,2,3,4],[25,5,47,54]]
a3=np.array(j)
print(a3)

[[ 1  2  3  4]
 [ 1  2  3  4]
 [25  5 47 54]]


In [134]:
a=np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [136]:
a=np.arange(100).reshape(2,50)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
  98 99]]


In [137]:
a=np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [138]:
a=np.arange(100).reshape(50,2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]
 [50 51]
 [52 53]
 [54 55]
 [56 57]
 [58 59]
 [60 61]
 [62 63]
 [64 65]
 [66 67]
 [68 69]
 [70 71]
 [72 73]
 [74 75]
 [76 77]
 [78 79]
 [80 81]
 [82 83]
 [84 85]
 [86 87]
 [88 89]
 [90 91]
 [92 93]
 [94 95]
 [96 97]
 [98 99]]


In [139]:
a=np.arange(100).reshape(5,20)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [140]:
b=np.arange(20,30).reshape(2,5)
print(b)

[[20 21 22 23 24]
 [25 26 27 28 29]]


In [153]:
a1=np.arange(22,28).reshape(2,3)
a2=np.arange(1,7).reshape(2,3)
a3=np.arange(22,28).reshape(2,3)
print(a1)
print('\n')
print(a2)
print('\n')
print(a3)

[[22 23 24]
 [25 26 27]]


[[1 2 3]
 [4 5 6]]


[[22 23 24]
 [25 26 27]]


In [154]:
a1+a2

array([[23, 25, 27],
       [29, 31, 33]])

In [155]:
a1-a2

array([[21, 21, 21],
       [21, 21, 21]])

In [156]:
a1*a2

array([[ 22,  46,  72],
       [100, 130, 162]])

In [157]:
print(a1.dtype)

int32


In [158]:
print(sqrt(a1))

[[484 529 576]
 [625 676 729]]


In [159]:
print(np.shape(a1))

(2, 3)
